typography_spectrum: 0.963560544885695
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.02478790213353932
analytics:
  google: null
  facebook: null
  twitter: null
name: gianennio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
